### ISSUE TITLE
KeyError: "None of [Index(['null'], dtype='object')] are in the [columns]"

### ISSUE THREAD

**Issue by feather-W** [CHPGenetics/GMM-demux#10]
Hi,

I encountered some error when I used GMM-demux as follows:

GMM-demux hto_gz null -u 2000 -r gmm_demux_hadge_process_report.txt --full gmm_demux_hadge_process -o gmm_demux_hadge_process  -t 0.8
==============================GMM-Demux Initialization==============================
Confidence threshold: 0.8
Output directory: gmm_demux_hadge_process
Traceback (most recent call last):
  File "/dssg/home/acct-medzy/medzy-pu/.local/bin/GMM-demux", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/dssg/home/acct-medzy/medzy-pu/.local/lib/python3.12/site-packages/GMM_Demux/GMM_Demux.py", line 65, in main
    full_df, GMM_df = GMM_IO.read_cellranger(input_path, hto_array)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dssg/home/acct-medzy/medzy-pu/.local/lib/python3.12/site-packages/GMM_Demux/GMM_IO.py", line 48, in read_cellranger
    data_df = full_df[hto_array]
              ~~~~~~~^^^^^^^^^^^
  File "/dssg/home/acct-medzy/medzy-pu/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 4108, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dssg/home/acct-medzy/medzy-pu/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 6200, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/dssg/home/acct-medzy/medzy-pu/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 6249, in _raise_if_missing
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['null'], dtype='object')] are in the [columns]"

Any idea why this might be happening?

Thank you very much in advance.

**Comment by cfsullivan16** [comment]
Did you ever find a solution? I am having the same exact problem currently while trying to set up the hadge pipeline. I wonder if it is a package version issue?

edit: it seems like a hadge issue in which the barcode names are not being properly input and "null" is being input instead, but I am still not sure how to fix this
